import {
  Box,
  Boxes,
  Factory,
  LayoutDashboard,
  Package,
  Ruler,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Users,
  Warehouse,
  MapPin,
} from 'lucide-react';
import { PERMS } from '../../shared/constants/permissions';

export const NAV = [
  {
    key: 'dashboard',
    label: 'Dashboard',
    path: '/dashboard',
    icon: LayoutDashboard,
    requiredPerm: null,
  },
  {
    key: 'master-data',
    label: 'Master Data',
    path: '/master-data',
    icon: Boxes,
    requiredPerm: PERMS.MASTERDATA_READ,
    children: [
      { key: 'master-data-products', label: 'Products', path: '/master-data/products', icon: Package, requiredPerm: PERMS.MASTERDATA_READ },
      { key: 'master-data-uom', label: 'UOM', path: '/master-data/uom', icon: Ruler, requiredPerm: PERMS.MASTERDATA_READ },
      { key: 'master-data-partners', label: 'Partners', path: '/master-data/partners', icon: Users, requiredPerm: PERMS.MASTERDATA_READ },
    ],
  },
  {
    key: 'warehouse-setup',
    label: 'Warehouse Setup',
    path: '/warehouse-setup',
    icon: Warehouse,
    requiredPerm: PERMS.WAREHOUSE_SETUP_READ,
    children: [
      {
        key: 'warehouse-setup-warehouses',
        label: 'Warehouses',
        path: '/warehouse-setup/warehouses',
        icon: Warehouse,
        requiredPerm: PERMS.WAREHOUSE_SETUP_READ,
      },
      {
        key: 'warehouse-setup-locations',
        label: 'Locations',
        path: '/warehouse-setup/locations',
        icon: MapPin,
        requiredPerm: PERMS.WAREHOUSE_SETUP_READ,
      },
      {
        key: 'warehouse-setup-zones',
        label: 'Zones',
        path: '/warehouse-setup/zones',
        icon: Box,
        requiredPerm: PERMS.WAREHOUSE_SETUP_READ,
      },
    ],
  },
  {
    key: 'purchasing',
    label: 'Purchasing',
    path: '/purchasing',
    icon: ShoppingCart,
    requiredPerm: PERMS.PURCHASING_READ,
  },
  {
    key: 'inventory',
    label: 'Inventory',
    path: '/inventory',
    icon: Warehouse,
    requiredPerm: PERMS.INVENTORY_READ,
  },
  {
    key: 'manufacturing',
    label: 'Manufacturing',
    path: '/manufacturing',
    icon: Factory,
    requiredPerm: PERMS.MANUFACTURING_READ,
  },
  {
    key: 'compliance',
    label: 'Compliance',
    path: '/compliance',
    icon: ShieldCheck,
    requiredPerm: PERMS.COMPLIANCE_READ,
  },
  {
    key: 'settings',
    label: 'Settings',
    path: '/settings',
    icon: Settings,
    requiredPerm: null,
  },
];
